<div class="row">
	<!-- LISTA DE MINISTÉRIOS -->
	<div class="col-xs-12 col-sm-12 col-md-9">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Servo</th>
					<th>Data de Nascimento</th>
					<th>Ativo</th>
					<th>&nbsp;</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->servos as $key => $servo): ?>
				<tr>
					<td><?=$servo['nome'];?></td>
					<td><?=$servo['data_nasc'];?></td>
					<td><?=$servo['servo_ativo'];?></td>
					<!-- <td><button class="btn btn-primary btn-sm"><span class="glyphicon glyphicon-pencil"></span></button></td> -->
					<td><a href="/servos/remove/<?=$servo['servo_id'];?>" class="btn btn-primary btn-sm">
						<span class="glyphicon glyphicon-remove"></span></a>
					</td>
				</tr>
				<?php endforeach;?>
			</tbody>
		</table>
	</div>
	<!-- ENDS LISTA DE MINISTÉRIOS -->
	
	<!-- OPÇÕES -->
	<div class="col-xs-12 col-sm-12 col-md-3">
		<!-- PESQUISAR -->
		<?=$this->filter();?>
		<!-- ENDS PESQUISAR -->
	
		<!-- NOVO -->
		
		<!-- ENDS NOVO -->
	</div>
	<!-- ENDS OPÇÕES -->
</div>