<div class="row">
	<header>
		<nav class="navbar navbar-inverse" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<a class="navbar-brand" href="/">goNSVitórias</a>
				</div>
				<div class="collapse navbar-collapse navbar-right">
					<ul class="nav navbar-nav">
						<li><a href="#">login</a></li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	
	<div class="container home-content">
		<div class="row banner-grupo">
			<div class="subtitle">Grupo de Oração</div>
			<div class="title">Nossa Senhora das Vitórias</div>
		</div>
	</div>
</div>