<div class="row">
	<header>
		<nav class="navbar navbar-inverse" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<a class="navbar-brand" href="/">goNSVitórias</a>
				</div>
				<div class="collapse navbar-collapse navbar-right">
					<form action="<?=$this->form->getAction();?>" name="<?=$this->form->getName();?>" method="<?=$this->form->getMethod();?>" role="<?=$this->form->getAttrib('role');?>">
					
					</form>
				</div>
			</div>
		</nav>
	</header>
	
	<div class="container home-content">
		<div class="row banner-grupo">
			<div class="subtitle">Grupo de Oração</div>
			<div class="title">Nossa Senhora das Vitórias</div>
		</div>
	</div>
</div>