<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>page title</title>
	</head>
	<body>
		<h1>An error occurred</h1>
		<h2><?=$this->message;?></h2>
		
		<?php if(isset($this->exception)): ?>
		
		<h3>Exception information:</h3>
		<p>
			<b>Message:</b>
			<?=$this->exception->getMessage();?>
		</p>
		
		<h3>Stach trace:</h3>
		<pre><?=$this->exception->getTraceAsString(); ?></pre>
		
		<h3>Request Parameters:</h3>
		<pre><?=var_export($this->request->getParams(), true); ?></pre>
		
		<?php endif; ?>
	</body>
</html>