<div class="row">
	<!-- LISTA DE MINISTÉRIOS -->
	<div class="col-xs-12 col-sm-12 col-md-9">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Ministério</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->ministerios as $key => $ministerio): ?>
				<tr>
					<td><?=$ministerio['ministerio_nome'];?></td>
					<td><button class="btn btn-primary btn-sm"><span class="glyphicon glyphicon-pencil"></span></button></td>
					<td><a href="/ministerios/remove/<?=$ministerio['ministerio_id'];?>" class="btn btn-primary btn-sm">
						<span class="glyphicon glyphicon-remove"></span></a>
					</td>
				</tr>
				<?php endforeach;?>
			</tbody>
		</table>
	</div>
	<!-- ENDS LISTA DE MINISTÉRIOS -->
	
	<!-- OPÇÕES -->
	<div class="col-xs-12 col-sm-12 col-md-3">
		<!-- PESQUISAR -->
		<?=$this->partial('/partial/pesquisar.phtml');?>
		<!-- ENDS PESQUISAR -->
	
		<!-- NOVO -->
		<?=$this->partial('/ministerios/novo.phtml', array('form' => $this->form));?>
		<!-- ENDS NOVO -->
	</div>
	<!-- ENDS OPÇÕES -->
</div>