<!-- NOVO MINISTÉRIO -->
<div class="box">
	<div class="box-header"><span class="glyphicon glyphicon-plus"></span> Novo ministério</div>
	<div class="box-content">
		<form action="<?=$this->form->getAction();?>" name="<?=$this->form->getName();?>" method="<?=$this->form->getMethod();?>" role="<?=$this->form->getAttrib('role');?>">
			<div class="form-group">
				<label class="sr-only" for="<?=$this->form->f_ministerio_nome->getAttrib('id');?>"><?=$this->form->f_ministerio_nome->getLabel();?></label>
				<?=$this->form->f_ministerio_nome;?>
			</div>
			<div class="text-right">
				<?=$this->form->submit;?>
			</div>			
		</form>
	</div>
</div>
<!-- ENDS NOVO MINISTÉRIO -->