<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-9">
		<table class="table table-striped table-condensed">
			<thead>
        		<tr>
        			<th>Nome</th>
        			<th>Nascimento</th>
        			<th>Telefone</th>
        			<th>Celular</th>
        			<th>E-mail</th>
        			<th>&nbsp;</th>
        			<th>&nbsp;</th>
        		</tr>
        	</thead>
        	<tbody>
        		<?php foreach($this->pessoas as $pessoa): ?>
        		<tr class="<?=($pessoa['ativo'] == 1) ? 'info' : '';?>">
        			<td><?=$pessoa['nome'];?></td>
        			<td><?=Util_Format_Date::DbToScreen($pessoa['data_nasc'], 'date');?></td>
        			<td><?=Util_Format_Number::toSimplePhone($pessoa['telefone']);?></td>
        			<td><?=Util_Format_Number::toSimplePhone($pessoa['celular']);?></td>
        			<td><?=$pessoa['email'];?></td>
        			<td><a href="/participantes/detalhes/<?=$pessoa['pessoa_id'];?>" class="btn btn-primary btn-sm fancybox" data-fancybox-type="iframe">
        				<span class="glyphicon glyphicon-list-alt"></span></a>
        			</td>
        			<td><a href="/participantes/cadastro/<?=$pessoa['pessoa_id'];?>" class="btn btn-primary btn-sm">
        				<span class="glyphicon glyphicon-pencil"></span></a>
        			</td>
        		</tr>
        		<?php endforeach; ?>
        	</tbody>
        </table>
	</div>
	
	<div class="col-xs-12 col-sm-12 col-md-3">
		<!-- PESQUISAR -->
		<?=$this->filter();?>
		<!-- ENDS PESQUISAR -->
	
		<!-- OPÇÕES -->
		<?=$this->partial('/participantes/opcoes.phtml');?>
		<!-- ENDS OPÇÕES -->
	</div>
</div>