<div class="row">
	<header>
		<nav class="navbar navbar-inverse" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<a class="navbar-brand" href="/">goNSVitórias</a>
				</div>
				<div class="collapse navbar-collapse navbar-right">
					<form action="<?=$this->form->getAction();?>" name="<?=$this->form->getName();?>" method="<?=$this->form->getMethod();?>" role="<?=$this->form->getAttrib('role');?>" class="form-inline">
						<div class="form-group">
							<label for="<?=$this->form->f_email->getAttrib('id');?>"><?=$this->form->f_email->getLabel();?></label>
							<?=$this->form->f_email;?>
						</div>
						<div class="form-group">
							<label for="<?=$this->form->f_senha->getAttrib('id');?>"><?=$this->form->f_senha->getLabel();?></label>
							<?=$this->form->f_senha;?>
						</div>
						<?=$this->form->submit;?>
					</form>
				</div>
			</div>
		</nav>
	</header>
	
	<div class="container home-content">
		<div class="row banner-grupo">
			<div class="subtitle">Grupo de Oração</div>
			<div class="title">Nossa Senhora das Vitórias</div>
		</div>
	</div>
</div>