<?php
    if(Zend_Auth::getInstance()->hasIdentity()){
        $usuario = Zend_Auth::getInstance()->getIdentity();
    }
?>
<header>
	<nav class="navbar navbar-inverse" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="/">goNSVitórias</a>
			</div>
			<div class="collapse navbar-collapse navbar-left">
				<ul class="nav navbar-nav">
					<li><a href="/dashboard">Dashboard</a></li>
					<li><a href="/participantes">Participantes</a></li>
				</ul>
			</div>
			<div class="collapse navbar-collapse navbar-right">
				<ul class="nav navbar-nav">
					<li class="dropdown">
						<div class="avatar"><img src="<?=Util_Helper::basePath('/img/site/person.png');?>" alt=""></div>
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							André <span class="caret"></span>
						</a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="#">Meus dados</a></li>
							<li><a href="#">Fazer logoff</a></li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
	</nav>
	
	<!-- PAGE TITLE -->
    <?php if($this->pageheader != ''):?>
    <div class="page-header">
    	<div class="container">
    		<h1><?=$this->pageheader;?><?php if($this->pagesubheader != ''):?> <small> - <?=$this->pagesubheader;?> - </small><?php endif;?></h1>
    	</div>
    </div>
	<?php endif;?>
    <!-- ENDS PAGE TITLE -->
</header>