<!-- application/layouts/scripts/layout.phtml -->
<?=$this->doctype();?>
<html lang="pt-BR">
    <head>
    	<!-- META TAGS -->
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    	<!-- ENDS META TAGS -->
    	
        <?=$this->headTitle();?>
		
        <!-- SHORTCUT ICON -->
        <link rel="shortcut icon" type="image/x-icon" href="<?=$this->baseUrl('/img/site/favicon.png'); ?>" />
        <!-- ENDS SHORTCUT ICON -->
		
        <!-- STYLESHEET -->
        <?=$this->partial('css.phtml', array('css' => $this->css)); ?>
        <!-- ENDS STYLESHEET -->
		
        <!-- SCRIPT -->
        <?=$this->partial('js.phtml', array('js' => $this->js)); ?>
        <!-- ENDS SCRIPT -->
    </head>
    <body>
    	<div id="page">
	        <!-- HEADER -->
	        <?=$this->partial('header.phtml', array('pageheader' => $this->pageheader));?>
	        <!-- ENDS HEADER -->
	        
	        <div class="container">			
	            <div class="row">
	                <div class="col-xs-12 col-sm-12 col-md-12">
	
	                    <!-- ALERT MESSAGE -->
	                    <?php if($this->alert != '' || is_array($this->alert)): ?>
	                    <div class="alert alert-<?=$this->alert['type'];?>"><?=$this->alert['message'];?></div>
	                    <?php endif; ?>
	                    <!-- ENDS ALERT MESSAGE -->
						
	                    <!-- CONTENT -->
	                    <?=$this->layout()->content; ?>
	                    <!-- ENDS CONTENT -->
						
	                </div>
	            </div>
	        </div>
	        
	        <!-- FOOTER -->
	        <?=$this->partial('footer.phtml');?>
	        <!-- ENDS FOOTER -->
        </div>
    </body>
</html>