<?php /*
<form action="<?=$this->form->getAction();?>" name="<?=$this->form->getName();?>" method="<?=$this->form->getMethod();?>" role="<?=$this->form->getAttrib('role');?>">
	<h3>Filtrar</h3>
	<div class="row">
		<div class="col-md-6">
			<div class="input-group">
				<?=$this->form->f_filter;?>
				<span class="input-group-addon glyphicon glyphicon-search"></span>
			</div>
		</div>
	</div>
</form>
*/ ?>


<!-- PESQUISAR -->
<div class="box">
	<div class="box-header"><span class="glyphicon glyphicon-search"></span> Pesquisar</div>
	<div class="box-content">
		<?=$this->form->f_filter;?>
	</div>
</div>
<!-- ENDS PESQUISAR -->